import { Inter } from "next/font/google";
import AgentNav from "@/components/agent-nav";
import AuthWrpaer from "./auth-wraper";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <AuthWrpaer>{children}</AuthWrpaer>;
}
